[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ligojcli", "ligojcli.plugins"]

[project]
name = "ligoj-cli"
version = "1.0.0"
description = "Ligoj CLI"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
authors = [{ name = "Fabrice Daugan", email = "fdaugan@kloudy.io" }]
dependencies = [
    "colorama==0.4.6",
    "requests==2.32.4",
    "dnspython==2.7.0",
    "pyyaml==6.0.2",
    "configparser==7.2.0",
    "unidecode==1.4.0",
    "jsonschema===4.25.0",
    "jsonmerge==1.9.2",
    "Jinja2==3.1.6",
    "pytimeparse==1.1.8"
]

[project.scripts]
ligoj = "ligojcli.ligoj:ligoj"

[project.urls]
Homepage = "https://github.com/ligoj/cli"
Documentation = "https://github.com/ligoj/cli/README.md"
Repository = "https://github.com/ligoj/cli"
Issues = "https://github.com/ligoj/cli/issues"